-- Migration: Add mcp_auth_tokens table for storing user authentication tokens
-- Author: Generated by Claude Code
-- Date: 2025-11-10

-- Create table to store user authentication tokens for MCP servers
CREATE TABLE IF NOT EXISTS mcp_auth_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    mcp_server_id INTEGER NOT NULL,
    token_encrypted TEXT NOT NULL,  -- Encrypted token for security
    token_hint TEXT,                -- Last 4 characters or hint for user to identify
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP,

    -- Foreign keys
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id) ON DELETE CASCADE,

    -- Unique constraint: one token per user per MCP server
    UNIQUE(user_id, mcp_server_id)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_mcp_auth_tokens_user_server
ON mcp_auth_tokens(user_id, mcp_server_id);

-- Create index for user lookups
CREATE INDEX IF NOT EXISTS idx_mcp_auth_tokens_user
ON mcp_auth_tokens(user_id);

-- Trigger to update updated_at timestamp
CREATE TRIGGER IF NOT EXISTS update_mcp_auth_tokens_timestamp
AFTER UPDATE ON mcp_auth_tokens
BEGIN
    UPDATE mcp_auth_tokens SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
