-- Migration: Add notifications table for user notifications
-- Author: Generated by Claude Code
-- Date: 2025-11-20

-- Create table to store user notifications
CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,          -- 알림을 받는 유저
    type VARCHAR(50) NOT NULL,         -- 'comment', 'favorite', 'status_change', 'new_mcp'
    message TEXT NOT NULL,              -- 알림 메시지
    is_read BOOLEAN DEFAULT 0 NOT NULL, -- 읽음 여부 (0: 안 읽음, 1: 읽음)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- 관련 정보 (선택적)
    mcp_server_id INTEGER,             -- 관련 MCP 서버
    related_user_id INTEGER,           -- 액션을 수행한 유저

    -- Foreign keys
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id) ON DELETE CASCADE,
    FOREIGN KEY (related_user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Create index for faster lookups by user
CREATE INDEX IF NOT EXISTS idx_notifications_user
ON notifications(user_id);

-- Create index for unread notifications
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
ON notifications(user_id, is_read);

-- Create index for created_at for ordering
CREATE INDEX IF NOT EXISTS idx_notifications_created_at
ON notifications(created_at DESC);
