"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 번역 데이터
const translations: Record<Language, Record<string, string>> = {
  ko: {
    // Navbar
    'nav.register': 'Register',
    'nav.mypage': 'My Page',
    'nav.signout': 'Sign Out',
    'nav.signin': 'Sign In',
    'nav.signInRequired': '로그인 필요',
    'nav.signInRequiredDesc': '새로운 MCP 서버를 등록하려면 로그인이 필요합니다.',
    'nav.cancel': '취소',
    'nav.wiki': 'Wiki',
    'nav.gettingStarted': 'Getting Started',
    'nav.howToUse': 'How to Use',
    'nav.roadmap': 'Roadmap',
    
    // MyPage
    'mypage.title': 'My Page',
    'mypage.welcome': '안녕하세요, {username}님! 등록한 서버와 즐겨찾기를 관리하세요.',
    'mypage.myServers': '내가 등록한 서버',
    'mypage.favorites': '즐겨찾기',
    'mypage.pending': '승인 대기중',
    'mypage.pendingBadge': '승인 대기중',
    'mypage.pendingServers': '승인 대기중인 서버 ({count}개)',
    'mypage.approvedServers': '등록된 서버 ({count}개)',
    'mypage.loading': '로딩 중...',
    'mypage.noServers': '등록한 서버가 없습니다',
    'mypage.noServersDesc': '새로운 MCP 서버를 등록해보세요!',
    'mypage.registerServer': '서버 등록하기',
    'mypage.noFavorites': '즐겨찾기한 서버가 없습니다',
    'mypage.noFavoritesDesc': '마음에 드는 MCP 서버에 즐겨찾기를 추가해보세요!',
    'mypage.browse': '서버 둘러보기',
    'mypage.noPending': '승인 대기중인 서버가 없습니다',
    'mypage.noPendingDesc': '모든 MCP 서버가 승인되었습니다.',
    'mypage.pendingCount': '승인 대기중인 서버 ({count}개)',
    'mypage.approveAll': '전체 승인',
    'mypage.approveConfirm': '정말 승인하시겠습니까?',
    'mypage.rejectConfirm': '정말로 이 서버를 거부하시겠습니까?',
    'mypage.approveFailed': '승인에 실패했습니다.',
    'mypage.approveError': '승인 중 오류가 발생했습니다.',
    'mypage.rejectFailed': '거부에 실패했습니다.',
    'mypage.rejectError': '거부 중 오류가 발생했습니다.',
    
    // User Page
    'userpage.loading': '{username}의 서버 목록을 불러오는 중...',
    'userpage.userNotFound': '사용자를 찾을 수 없습니다.',
    'userpage.loadError': '서버 목록을 불러오는 중 오류가 발생했습니다.',
    'userpage.goBack': '뒤로 가기',
    'userpage.title': '{username}의 MCP 서버',
    'userpage.totalServers': '총 {count}개의 서버가 등록되어 있습니다.',
    'userpage.noServers': '등록된 MCP 서버가 없습니다.',
    'userpage.viewMore': 'VIEW MORE',
    
    // Comments
    'comments.title': '댓글',
    'comments.writeComment': '댓글을 작성해주세요...',
    'comments.loginRequired': '댓글을 작성하려면 로그인해주세요.',
    'comments.submitting': '작성 중...',
    'comments.submit': '작성',
    'comments.loading': '댓글을 불러오는 중...',
    'comments.noComments': '아직 댓글이 없습니다. 첫 번째 댓글을 작성해보세요!',
    'comments.edited': '(수정됨)',
    'comments.save': '저장',
    'comments.cancel': '취소',
    'comments.edit': '수정',
    'comments.delete': '삭제',
    'comments.deleteConfirm': '댓글을 삭제하시겠습니까?',
    'comments.justNow': '방금 전',
    'comments.hoursAgo': '{hours}시간 전',
    'comments.writeError': '댓글 작성 실패: {error}',
    'comments.writeErrorUnknown': '댓글 작성 중 오류가 발생했습니다.',
    'comments.editError': '댓글 수정 실패: {error}',
    'comments.editErrorUnknown': '댓글 수정 중 오류가 발생했습니다.',
    'comments.deleteError': '댓글 삭제 실패: {error}',
    'comments.deleteErrorUnknown': '댓글 삭제 중 오류가 발생했습니다.',
    
    // Signup Page
    'signup.title': '회원가입',
    'signup.subtitle': '추가 정보를 입력하여 회원가입을 완료하세요',
    'signup.knoxId': 'Knox ID',
    'signup.nickname': '닉네임',
    'signup.nicknamePlaceholder': '닉네임을 입력하세요',
    'signup.nicknameHelp': '닉네임은 공개됩니다. 비속어, 혐오 표현 사용은 제한됩니다.',
    'signup.bio': '자기소개',
    'signup.bioPlaceholder': '자기소개를 입력하세요 (선택사항)',
    'signup.submitting': '회원가입 중...',
    'signup.submit': '회원가입 완료',
    'signup.backToLogin': '로그인 페이지로 돌아가기',
    'signup.error': '회원가입에 실패했습니다.',
    'signup.unknownError': '알 수 없는 오류가 발생했습니다.',
    
    // Main Page Ranking
    'ranking.top3': 'Top 3',
    'ranking.latest': '최신 등록',
    'ranking.topUsers': 'Top Users',
    'ranking.favorites': 'favorites',
    'ranking.servers': 'servers',
    'ranking.viewDetails': 'VIEW',
    'ranking.mcpDeveloper': 'MCP 서버 개발자',
    'ranking.serverCount': '{count}개 서버',
    'ranking.developer': '개발자',
    'ranking.viewProfile': 'VIEW',
    
    // Submit Page
    'submit.title': 'Register a New MCP Server',
    'submit.autoSaved': '자동 저장됨: {time}',
    'submit.serverName': 'Server Name',
    'submit.serverNameRequired': 'Server Name은 필수입니다.',
    'submit.serverNamePlaceholder': 'My MCP Server',
    'submit.githubLink': 'GitHub Link',
    'submit.githubLinkRequired': 'GitHub Link는 필수입니다.',
    'submit.githubLinkInvalid': '유효한 GitHub URL을 입력해주세요.',
    'submit.githubLinkPlaceholder': 'https://github.com/username/repository',
    'submit.description': 'Description',
    'submit.descriptionRequired': 'Description은 필수입니다.',
    'submit.descriptionPlaceholder': 'Describe your MCP server...',
    'submit.protocol': 'Transport Type',
    'submit.protocolRequired': 'Transport Type은 필수입니다.',
    'submit.protocolSelect': 'Select a transport type',
    'submit.serverUrl': 'Server URL',
    'submit.serverUrlInvalid': '유효한 URL을 입력해주세요.',
    'submit.serverUrlPlaceholderStdio': 'python stdio_test_mcp_server.py',
    'submit.serverUrlPlaceholderHttp': 'http://localhost:3000',
    'submit.serverUrlHelpStdio': 'MCP 서버 실행 명령어를 입력하세요. Transport Type과 함께 입력하면 자동으로 tools를 미리보기합니다.',
    'submit.serverUrlHelpHttp': 'MCP Server의 URL을 입력하세요. Transport Type과 함께 입력하면 자동으로 tools를 미리보기합니다.',
    'submit.serverConfig': 'Server Config (JSON)',
    'submit.serverConfigPlaceholder': '{"type": "streamable-http", "url": "http://localhost:3000"}',
    'submit.serverConfigHelp': 'MCP Server 설정을 JSON 형식으로 입력하세요.',
    'submit.serverConfigInvalid': 'Server Config JSON 형식이 올바르지 않습니다.',
    'submit.loadingTools': 'MCP Server에서 tools 정보를 가져오는 중...',
    'submit.toolsPreview': 'MCP Server Tools ({count}개)',
    'submit.addAllTools': '모두 추가',
    'submit.toolsAdded': '{count}개의 tools가 추가되었습니다.',
    'submit.noDescription': '설명 없음',
    'submit.parameters': 'Parameters:',
    'submit.required': 'required',
    'submit.connectionError': 'MCP Server에 연결할 수 없습니다. Server URL과 Transport Type을 확인하고 서버가 실행 중인지 확인해주세요.',
    'submit.stdioWarning': 'STDIO Transport 안내:',
    'submit.stdioWarningDesc1': 'STDIO Transport는 브라우저에서 직접 미리보기할 수 없습니다.',
    'submit.stdioWarningDesc2': '수동으로 tools를 추가해주세요.',
    'submit.tools': 'Tools ({count})',
    'submit.addTool': 'Add Tool',
    'submit.editTool': 'Edit Tool',
    'submit.addNewTool': 'Add New Tool',
    'submit.toolName': 'Tool Name',
    'submit.toolNameRequired': 'Tool name과 description은 필수입니다.',
    'submit.toolNamePlaceholder': 'tool_name',
    'submit.toolDescription': 'Description',
    'submit.toolDescriptionPlaceholder': 'Tool description...',
    'submit.addParameter': 'Add Parameter',
    'submit.editParameter': 'Edit Parameter',
    'submit.parameterName': 'Parameter name',
    'submit.parameterNameRequired': 'Parameter name은 필수입니다.',
    'submit.parameterDescription': 'Description (optional)',
    'submit.selectType': 'Select type',
    'submit.noType': 'no type',
    'submit.update': 'Update',
    'submit.add': 'Add',
    'submit.cancel': 'Cancel',
    'submit.updateTool': 'Update Tool',
    'submit.addToolButton': 'Add Tool',
    'submit.deleteToolConfirm': '이 tool을 삭제하시겠습니까?',
    'submit.submitting': '등록 중...',
    'submit.submitButton': 'MCP Server 등록',
    'submit.signInRequired': 'Sign in required.',
    'submit.checkingAuth': 'Checking authentication...',
    'submit.sessionExpired': 'Session Expired',
    'submit.draftSaved': 'Draft saved automatically.',
    'submit.loginAgain': 'Log in again to continue.',
    'submit.ok': 'OK',
    'submit.successTitle': 'MCP 서버 등록이 완료되었습니다.',
    'submit.successDesc1': '승인 후 MCP 목록에서 확인할 수 있으며,',
    'submit.successDesc2': '내 등록 서버는 My Page에서 확인하세요.',
    'submit.viewMcpList': 'MCP 목록 보기',
    'submit.viewMyPage': 'My Page',
    'submit.restorePrompt': '이전에 작성하던 내용이 있습니다. 복원하시겠습니까?',
    'submit.leaveConfirm': '작성 중인 내용이 자동 저장되었습니다.\n페이지를 벗어나시겠습니까?',
    
    // Edit Page
    'edit.title': 'Edit MCP Server',
    'edit.autoSaved': '자동 저장됨: {time}',
    'edit.loading': 'Loading MCP server...',
    'edit.notFound': 'MCP server not found',
    'edit.serverName': 'Server Name',
    'edit.githubLink': 'GitHub Link',
    'edit.description': 'Description',
    'edit.descriptionRequired': 'Description은 필수입니다.',
    'edit.descriptionPlaceholder': 'MCP 서버에 대한 상세한 설명을 입력하세요',
    'edit.protocol': 'Transport Type',
    'edit.protocolRequired': 'Transport Type은 필수입니다.',
    'edit.protocolSelect': 'Select a transport type',
    'edit.serverUrl': 'Server URL',
    'edit.serverUrlInvalid': '유효한 URL을 입력해주세요.',
    'edit.serverUrlPlaceholderStdio': 'python stdio_test_mcp_server.py',
    'edit.serverUrlPlaceholderHttp': 'http://localhost:3000',
    'edit.serverUrlHelpStdio': 'MCP 서버 실행 명령어를 입력하세요.',
    'edit.serverUrlHelpHttp': 'MCP Server의 URL을 입력하세요.',
    'edit.serverConfig': 'Server Config (JSON)',
    'edit.serverConfigPlaceholder': '{"mcpServers": {"example": {"command": "python", "args": ["server.py"]}}}',
    'edit.serverConfigHelp': 'JSON 형식으로 서버 설정을 입력하세요. 비워두면 기본 설정이 사용됩니다.',
    'edit.serverConfigInvalid': 'Server Config JSON 형식이 올바르지 않습니다.',
    'edit.loadingTools': 'MCP Server에서 tools 정보를 가져오는 중...',
    'edit.toolsPreview': 'MCP Server Tools ({count}개)',
    'edit.addAllTools': '모두 추가',
    'edit.toolsAdded': '{count}개의 tools가 추가되었습니다.',
    'edit.noDescription': '설명 없음',
    'edit.connectionError': 'MCP Server에 연결할 수 없습니다. Server URL과 Transport Type을 확인하고 서버가 실행 중인지 확인해주세요.',
    'edit.duplicateToolsTitle': '중복된 Tool이 발견되었습니다',
    'edit.duplicateToolsDesc': '동일한 이름의 tool이 이미 존재합니다. 각 tool마다 어떤 것을 사용할지 선택해주세요.',
    'edit.existingTool': '기존 Tool',
    'edit.newTool': '새로운 Tool',
    'edit.applyChoices': '선택 적용',
    'edit.stdioWarning': 'STDIO Transport 안내:',
    'edit.stdioWarningDesc1': 'STDIO Transport는 브라우저에서 직접 미리보기할 수 없습니다.',
    'edit.stdioWarningDesc2': '수동으로 tools를 추가해주세요.',
    'edit.tools': 'Tools ({count})',
    'edit.addTool': 'Add Tool',
    'edit.editTool': 'Edit Tool',
    'edit.addNewTool': 'Add New Tool',
    'edit.toolName': 'Tool Name',
    'edit.toolNameRequired': 'Tool name과 description은 필수입니다.',
    'edit.toolNamePlaceholder': 'tool_name',
    'edit.toolDescription': 'Description',
    'edit.toolDescriptionPlaceholder': 'Tool description...',
    'edit.parameters': 'Parameters',
    'edit.addParameter': 'Add Parameter',
    'edit.editParameter': 'Edit Parameter',
    'edit.parameterName': 'Parameter name',
    'edit.parameterNameRequired': 'Parameter name은 필수입니다.',
    'edit.parameterDescription': 'Description (optional)',
    'edit.selectType': 'Select type',
    'edit.noType': 'no type',
    'edit.required': 'required',
    'edit.update': 'Update',
    'edit.add': 'Add',
    'edit.cancel': 'Cancel',
    'edit.updateTool': 'Update Tool',
    'edit.addToolButton': 'Add Tool',
    'edit.deleteToolConfirm': '이 tool을 삭제하시겠습니까?',
    'edit.cancelButton': 'Cancel',
    'edit.updating': 'Updating...',
    'edit.updateButton': 'Update Server',
    'edit.sessionExpired': 'Session Expired',
    'edit.draftSaved': 'Draft saved automatically.',
    'edit.loginAgain': 'Log in again to continue.',
    'edit.ok': 'OK',
    'edit.successTitle': 'MCP 서버 수정이 완료되었습니다.',
    'edit.successDesc1': '수정된 내용이 반영되었으며,',
    'edit.successDesc2': 'MCP 목록에서 확인할 수 있습니다.',
    'edit.viewDetail': '상세 페이지 보기',
    'edit.viewMcpList': 'MCP 목록 보기',
    'edit.restorePrompt': '이전에 수정하던 내용이 있습니다. 복원하시겠습니까?',
    'edit.leaveConfirm': '수정 중인 내용이 자동 저장되었습니다.\n페이지를 벗어나시겠습니까?',
  },
  en: {
    // Navbar
    'nav.register': 'Register',
    'nav.mypage': 'My Page',
    'nav.signout': 'Sign Out',
    'nav.signin': 'Sign In',
    'nav.signInRequired': 'Sign In Required',
    'nav.signInRequiredDesc': 'You need to sign in to register a new MCP server.',
    'nav.cancel': 'Cancel',
    'nav.wiki': 'Wiki',
    'nav.gettingStarted': 'Getting Started',
    'nav.howToUse': 'How to Use',
    'nav.roadmap': 'Roadmap',
    
    // MyPage
    'mypage.title': 'My Page',
    'mypage.welcome': 'Welcome, {username}! Manage your registered servers and favorites.',
    'mypage.myServers': 'My Servers',
    'mypage.favorites': 'Favorites',
    'mypage.pending': 'Pending Approval',
    'mypage.pendingBadge': 'Pending Approval',
    'mypage.pendingServers': 'Pending Servers ({count})',
    'mypage.approvedServers': 'Registered Servers ({count})',
    'mypage.loading': 'Loading...',
    'mypage.noServers': 'No registered servers',
    'mypage.noServersDesc': 'Register a new MCP server!',
    'mypage.registerServer': 'Register Server',
    'mypage.noFavorites': 'No favorite servers',
    'mypage.noFavoritesDesc': 'Add your favorite MCP servers to your favorites!',
    'mypage.browse': 'Browse Servers',
    'mypage.noPending': 'No pending servers',
    'mypage.noPendingDesc': 'All MCP servers have been approved.',
    'mypage.pendingCount': 'Pending Servers ({count})',
    'mypage.approveAll': 'Approve All',
    'mypage.approveConfirm': 'Are you sure you want to approve this server?',
    'mypage.rejectConfirm': 'Are you sure you want to reject this server?',
    'mypage.approveFailed': 'Failed to approve.',
    'mypage.approveError': 'An error occurred during approval.',
    'mypage.rejectFailed': 'Failed to reject.',
    'mypage.rejectError': 'An error occurred during rejection.',
    
    // User Page
    'userpage.loading': 'Loading {username}\'s servers...',
    'userpage.userNotFound': 'User not found.',
    'userpage.loadError': 'An error occurred while loading the server list.',
    'userpage.goBack': 'Go Back',
    'userpage.title': '{username}\'s MCP Servers',
    'userpage.totalServers': 'Total {count} servers registered.',
    'userpage.noServers': 'No MCP servers registered.',
    'userpage.viewMore': 'VIEW MORE',
    
    // Comments
    'comments.title': 'Comments',
    'comments.writeComment': 'Write a comment...',
    'comments.loginRequired': 'Please log in to write a comment.',
    'comments.submitting': 'Submitting...',
    'comments.submit': 'Submit',
    'comments.loading': 'Loading comments...',
    'comments.noComments': 'No comments yet. Be the first to comment!',
    'comments.edited': '(edited)',
    'comments.save': 'Save',
    'comments.cancel': 'Cancel',
    'comments.edit': 'Edit',
    'comments.delete': 'Delete',
    'comments.deleteConfirm': 'Are you sure you want to delete this comment?',
    'comments.justNow': 'Just now',
    'comments.hoursAgo': '{hours} hours ago',
    'comments.writeError': 'Failed to write comment: {error}',
    'comments.writeErrorUnknown': 'An error occurred while writing the comment.',
    'comments.editError': 'Failed to edit comment: {error}',
    'comments.editErrorUnknown': 'An error occurred while editing the comment.',
    'comments.deleteError': 'Failed to delete comment: {error}',
    'comments.deleteErrorUnknown': 'An error occurred while deleting the comment.',
    
    // Signup Page
    'signup.title': 'Sign Up',
    'signup.subtitle': 'Complete your registration by entering additional information',
    'signup.knoxId': 'Knox ID',
    'signup.nickname': 'Nickname',
    'signup.nicknamePlaceholder': 'Enter your nickname',
    'signup.nicknameHelp': 'Your nickname will be public. Profanity and hate speech are prohibited.',
    'signup.bio': 'Bio',
    'signup.bioPlaceholder': 'Enter your bio (optional)',
    'signup.submitting': 'Signing up...',
    'signup.submit': 'Complete Sign Up',
    'signup.backToLogin': 'Back to Login',
    'signup.error': 'Sign up failed.',
    'signup.unknownError': 'An unknown error occurred.',
    
    // Main Page Ranking
    'ranking.top3': 'Top 3',
    'ranking.latest': 'Latest',
    'ranking.topUsers': 'Top Users',
    'ranking.favorites': 'favorites',
    'ranking.servers': 'servers',
    'ranking.viewDetails': 'VIEW',
    'ranking.mcpDeveloper': 'MCP Server Developer',
    'ranking.serverCount': '{count} servers',
    'ranking.developer': 'Developer',
    'ranking.viewProfile': 'VIEW',
    
    // Submit Page
    'submit.title': 'Register a New MCP Server',
    'submit.autoSaved': 'Auto-saved: {time}',
    'submit.serverName': 'Server Name',
    'submit.serverNameRequired': 'Server Name is required.',
    'submit.serverNamePlaceholder': 'My MCP Server',
    'submit.githubLink': 'GitHub Link',
    'submit.githubLinkRequired': 'GitHub Link is required.',
    'submit.githubLinkInvalid': 'Please enter a valid GitHub URL.',
    'submit.githubLinkPlaceholder': 'https://github.com/username/repository',
    'submit.description': 'Description',
    'submit.descriptionRequired': 'Description is required.',
    'submit.descriptionPlaceholder': 'Describe your MCP server...',
    'submit.protocol': 'Transport Type',
    'submit.protocolRequired': 'Transport Type is required.',
    'submit.protocolSelect': 'Select a transport type',
    'submit.serverUrl': 'Server URL',
    'submit.serverUrlInvalid': 'Please enter a valid URL.',
    'submit.serverUrlPlaceholderStdio': 'python stdio_test_mcp_server.py',
    'submit.serverUrlPlaceholderHttp': 'http://localhost:3000',
    'submit.serverUrlHelpStdio': 'Enter the MCP server run command. When entered with Transport Type, tools will be previewed automatically.',
    'submit.serverUrlHelpHttp': 'Enter the MCP Server URL. When entered with Transport Type, tools will be previewed automatically.',
    'submit.serverConfig': 'Server Config (JSON)',
    'submit.serverConfigPlaceholder': '{"type": "streamable-http", "url": "http://localhost:3000"}',
    'submit.serverConfigHelp': 'Enter MCP Server configuration in JSON format.',
    'submit.serverConfigInvalid': 'Server Config JSON format is invalid.',
    'submit.loadingTools': 'Loading tools from MCP Server...',
    'submit.toolsPreview': 'MCP Server Tools ({count})',
    'submit.addAllTools': 'Add All',
    'submit.toolsAdded': '{count} tools have been added.',
    'submit.noDescription': 'No description',
    'submit.parameters': 'Parameters:',
    'submit.required': 'required',
    'submit.connectionError': 'Cannot connect to MCP Server. Please check the Server URL and Transport Type, and ensure the server is running.',
    'submit.stdioWarning': 'STDIO Transport Notice:',
    'submit.stdioWarningDesc1': 'STDIO transport cannot be previewed directly in the browser.',
    'submit.stdioWarningDesc2': 'Please add tools manually.',
    'submit.tools': 'Tools ({count})',
    'submit.addTool': 'Add Tool',
    'submit.editTool': 'Edit Tool',
    'submit.addNewTool': 'Add New Tool',
    'submit.toolName': 'Tool Name',
    'submit.toolNameRequired': 'Tool name and description are required.',
    'submit.toolNamePlaceholder': 'tool_name',
    'submit.toolDescription': 'Description',
    'submit.toolDescriptionPlaceholder': 'Tool description...',
    'submit.addParameter': 'Add Parameter',
    'submit.editParameter': 'Edit Parameter',
    'submit.parameterName': 'Parameter name',
    'submit.parameterNameRequired': 'Parameter name is required.',
    'submit.parameterDescription': 'Description (optional)',
    'submit.selectType': 'Select type',
    'submit.noType': 'no type',
    'submit.update': 'Update',
    'submit.add': 'Add',
    'submit.cancel': 'Cancel',
    'submit.updateTool': 'Update Tool',
    'submit.addToolButton': 'Add Tool',
    'submit.deleteToolConfirm': 'Are you sure you want to delete this tool?',
    'submit.submitting': 'Submitting...',
    'submit.submitButton': 'Register MCP Server',
    'submit.signInRequired': 'Sign in required.',
    'submit.checkingAuth': 'Checking authentication...',
    'submit.sessionExpired': 'Session Expired',
    'submit.draftSaved': 'Draft saved automatically.',
    'submit.loginAgain': 'Log in again to continue.',
    'submit.ok': 'OK',
    'submit.successTitle': 'MCP Server registration completed.',
    'submit.successDesc1': 'After approval, it can be viewed in the MCP list,',
    'submit.successDesc2': 'and your registered servers can be found on My Page.',
    'submit.viewMcpList': 'View MCP List',
    'submit.viewMyPage': 'My Page',
    'submit.restorePrompt': 'You have unsaved work. Do you want to restore it?',
    'submit.leaveConfirm': 'Your work has been auto-saved.\nDo you want to leave this page?',
    
    // Edit Page
    'edit.title': 'Edit MCP Server',
    'edit.autoSaved': 'Auto-saved: {time}',
    'edit.loading': 'Loading MCP server...',
    'edit.notFound': 'MCP server not found',
    'edit.serverName': 'Server Name',
    'edit.githubLink': 'GitHub Link',
    'edit.description': 'Description',
    'edit.descriptionRequired': 'Description is required.',
    'edit.descriptionPlaceholder': 'Enter a detailed description of your MCP server',
    'edit.protocol': 'Transport Type',
    'edit.protocolRequired': 'Transport Type is required.',
    'edit.protocolSelect': 'Select a transport type',
    'edit.serverUrl': 'Server URL',
    'edit.serverUrlInvalid': 'Please enter a valid URL.',
    'edit.serverUrlPlaceholderStdio': 'python stdio_test_mcp_server.py',
    'edit.serverUrlPlaceholderHttp': 'http://localhost:3000',
    'edit.serverUrlHelpStdio': 'Enter the MCP server run command.',
    'edit.serverUrlHelpHttp': 'Enter the MCP Server URL.',
    'edit.serverConfig': 'Server Config (JSON)',
    'edit.serverConfigPlaceholder': '{"mcpServers": {"example": {"command": "python", "args": ["server.py"]}}}',
    'edit.serverConfigHelp': 'Enter server configuration in JSON format. Default configuration will be used if left blank.',
    'edit.serverConfigInvalid': 'Server Config JSON format is invalid.',
    'edit.loadingTools': 'Loading tools from MCP Server...',
    'edit.toolsPreview': 'MCP Server Tools ({count})',
    'edit.addAllTools': 'Add All',
    'edit.toolsAdded': '{count} tools have been added.',
    'edit.noDescription': 'No description',
    'edit.connectionError': 'Cannot connect to MCP Server. Please check the Server URL and Transport Type, and ensure the server is running.',
    'edit.duplicateToolsTitle': 'Duplicate Tools Found',
    'edit.duplicateToolsDesc': 'Tools with the same name already exist. Please select which version to use for each tool.',
    'edit.existingTool': 'Existing Tool',
    'edit.newTool': 'New Tool',
    'edit.applyChoices': 'Apply Choices',
    'edit.stdioWarning': 'STDIO Transport Notice:',
    'edit.stdioWarningDesc1': 'STDIO transport cannot be previewed directly in the browser.',
    'edit.stdioWarningDesc2': 'Please add tools manually.',
    'edit.tools': 'Tools ({count})',
    'edit.addTool': 'Add Tool',
    'edit.editTool': 'Edit Tool',
    'edit.addNewTool': 'Add New Tool',
    'edit.toolName': 'Tool Name',
    'edit.toolNameRequired': 'Tool name and description are required.',
    'edit.toolNamePlaceholder': 'tool_name',
    'edit.toolDescription': 'Description',
    'edit.toolDescriptionPlaceholder': 'Tool description...',
    'edit.parameters': 'Parameters',
    'edit.addParameter': 'Add Parameter',
    'edit.editParameter': 'Edit Parameter',
    'edit.parameterName': 'Parameter name',
    'edit.parameterNameRequired': 'Parameter name is required.',
    'edit.parameterDescription': 'Description (optional)',
    'edit.selectType': 'Select type',
    'edit.noType': 'no type',
    'edit.required': 'required',
    'edit.update': 'Update',
    'edit.add': 'Add',
    'edit.cancel': 'Cancel',
    'edit.updateTool': 'Update Tool',
    'edit.addToolButton': 'Add Tool',
    'edit.deleteToolConfirm': 'Are you sure you want to delete this tool?',
    'edit.cancelButton': 'Cancel',
    'edit.updating': 'Updating...',
    'edit.updateButton': 'Update Server',
    'edit.sessionExpired': 'Session Expired',
    'edit.draftSaved': 'Draft saved automatically.',
    'edit.loginAgain': 'Log in again to continue.',
    'edit.ok': 'OK',
    'edit.successTitle': 'MCP Server update completed.',
    'edit.successDesc1': 'Changes have been applied,',
    'edit.successDesc2': 'and can be viewed in the MCP list.',
    'edit.viewDetail': 'View Detail',
    'edit.viewMcpList': 'View MCP List',
    'edit.restorePrompt': 'You have unsaved edits. Do you want to restore them?',
    'edit.leaveConfirm': 'Your edits have been auto-saved.\nDo you want to leave this page?',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ko');

  useEffect(() => {
    // 페이지 로드 시 localStorage에서 언어 설정 복원
    const storedLanguage = localStorage.getItem('language') as Language;
    if (storedLanguage && (storedLanguage === 'ko' || storedLanguage === 'en')) {
      setLanguageState(storedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, string>) => {
    let text = translations[language][key] || key;
    
    // 파라미터 치환
    if (params) {
      Object.keys(params).forEach(paramKey => {
        text = text.replace(`{${paramKey}}`, params[paramKey]);
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

